import Foundation

/// Which build produced a report or deck, for the small "Generated by" stamp on exports.
public enum AppVersion {
    /// e.g. "RVTools Analyzer 1.0 (build 412, v1.0-3-g1a2b3c4)"; "-dirty" means built with uncommitted changes.
    public static let description: String = {
        let info = Bundle.main.infoDictionary ?? [:]
        // The app bundle: stamped by scripts/build-app.sh.
        if let build = info["RVTABuild"] as? String {
            let name = info["CFBundleName"] as? String ?? "RVTools Analyzer"
            let version = info["CFBundleShortVersionString"] as? String ?? ""
            let number = info["CFBundleVersion"] as? String
            return [name, version].filter { !$0.isEmpty }.joined(separator: " ") + " (" + [number.map { "build \($0)" }, build].compactMap { $0 }.joined(separator: ", ") + ")"
        }
        // rvtools-cli and rvtools-decks-server run from .build inside the checkout they were built from, so its commit
        // stands in for a stamp. It reflects the checkout now, which matches the binary as long as it was rebuilt after.
        let tool = Bundle.main.executableURL?.lastPathComponent ?? "rvtools-cli"
        if let root = packageRoot(), let commit = git(root, "describe", "--tags", "--always", "--dirty") {
            let number = git(root, "rev-list", "--count", "HEAD")
            return "RVTools Analyzer \(tool) (" + [number.map { "build \($0)" }, commit].compactMap { $0 }.joined(separator: ", ") + ")"
        }
        return "RVTools Analyzer \(tool) (unversioned build)"
    }()

    /// "Generated by … on <date>" for the end of a report or the corner of a cover slide.
    public static func generatedLine(_ date: Date = Date()) -> String {
        "Generated by \(description) on \(Fmt.dateTime(date)) UTC"
    }

    private static func packageRoot() -> URL? {
        guard var dir = Bundle.main.executableURL?.resolvingSymlinksInPath().deletingLastPathComponent() else { return nil }
        for _ in 0..<8 {
            if FileManager.default.fileExists(atPath: dir.appendingPathComponent("Package.swift").path) { return dir }
            dir.deleteLastPathComponent()
        }
        return nil
    }

    private static func git(_ root: URL, _ args: String...) -> String? {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        p.arguments = ["-C", root.path] + args
        let out = Pipe()
        p.standardOutput = out
        p.standardError = FileHandle.nullDevice
        guard (try? p.run()) != nil else { return nil }
        let data = out.fileHandleForReading.readDataToEndOfFile()
        p.waitUntilExit()
        let s = String(decoding: data, as: UTF8.self).trimmingCharacters(in: .whitespacesAndNewlines)
        return p.terminationStatus == 0 && !s.isEmpty ? s : nil
    }
}
